name 'tomcat'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures Apache Tomcat.'
long_description 'Application cookbook which installs and configures Apache Tomcat.'
version '1.0.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'scientific'
supports 'smartos'
supports 'ubuntu'

depends 'java'
depends 'libartifact'
depends 'poise', '~> 2.2'
depends 'poise-service', '~> 1.0'
